# Generated by Django 4.2.11 on 2024-03-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Country', models.CharField(default='中国', max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('Rank', models.IntegerField(blank=True, default=4)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Mobile', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('Landline', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('Time', models.DateTimeField()),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50, null=True, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Mobile', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('Landline', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Abstract', models.CharField(blank=True, max_length=100, null=True)),
                ('Introduction', models.CharField(max_length=500, null=True)),
                ('Class', models.SmallIntegerField(choices=[(2, '中医中药'), (0, '食品和农产品'), (3, '西医西药'), (1, '医疗器械'), (4, '健康服务管理')], default=0)),
                ('Figure', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.SmallIntegerField(choices=[(2, '中医中药'), (0, '食品和农产品'), (3, '西医西药'), (1, '医疗器械'), (4, '健康服务管理')], default=0)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.usermodel')),
            ],
        ),
    ]
