# Generated by Django 4.2.11 on 2024-03-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsModel',
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Class',
            field=models.SmallIntegerField(choices=[(1, '医疗器械'), (0, '食品和农产品'), (4, '健康服务管理'), (2, '中医中药'), (3, '西医西药')], default=0),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Status',
            field=models.SmallIntegerField(choices=[(1, '医疗器械'), (0, '食品和农产品'), (4, '健康服务管理'), (2, '中医中药'), (3, '西医西药')], default=0),
        ),
    ]
