# Generated by Django 4.2.11 on 2024-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_news_newsmodel_alter_companymodel_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='Class',
            field=models.SmallIntegerField(choices=[(0, '食品和农产品'), (3, '西医西药'), (4, '健康服务管理'), (2, '中医中药'), (1, '医疗器械')], default=0),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Status',
            field=models.SmallIntegerField(choices=[(0, '食品和农产品'), (3, '西医西药'), (4, '健康服务管理'), (2, '中医中药'), (1, '医疗器械')], default=0),
        ),
    ]
