# Generated by Django 4.2.11 on 2024-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_companymodel_class_alter_companymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='Figure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Class',
            field=models.SmallIntegerField(choices=[(0, '食品和农产品'), (2, '中医中药'), (4, '健康服务管理'), (1, '医疗器械'), (3, '西医西药')], default=0),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Introduction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Status',
            field=models.SmallIntegerField(choices=[(0, '食品和农产品'), (2, '中医中药'), (4, '健康服务管理'), (1, '医疗器械'), (3, '西医西药')], default=0),
        ),
    ]
