# Generated by Django 4.2.11 on 2024-04-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_newsmodel_figure_alter_companymodel_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Class',
            field=models.SmallIntegerField(choices=[(4, '健康服务管理'), (3, '西医西药'), (2, '中医中药'), (0, '食品和农产品'), (1, '医疗器械')], default=0),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Status',
            field=models.SmallIntegerField(choices=[(4, '健康服务管理'), (3, '西医西药'), (2, '中医中药'), (0, '食品和农产品'), (1, '医疗器械')], default=0),
        ),
    ]
