# Generated by Django 4.2.11 on 2024-04-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_companymodel_address_alter_companymodel_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='Class',
            field=models.SmallIntegerField(choices=[(4, '健康服务管理'), (0, '食品和农产品'), (1, '医疗器械'), (3, '西医西药'), (2, '中医中药')], default=0),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='CompanyName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Landline',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Status',
            field=models.SmallIntegerField(choices=[(4, '健康服务管理'), (0, '食品和农产品'), (1, '医疗器械'), (3, '西医西药'), (2, '中医中药')], default=0),
        ),
    ]
