# Generated by Django 4.2.11 on 2024-04-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_companymodel_class_alter_companymodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='Landline',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='Mobile',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='Abstract',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='Introduction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Class',
            field=models.SmallIntegerField(choices=[(3, '西医西药'), (0, '食品和农产品'), (1, '医疗器械'), (2, '中医中药'), (4, '健康服务管理')], default=0),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Status',
            field=models.SmallIntegerField(choices=[(3, '西医西药'), (0, '食品和农产品'), (1, '医疗器械'), (2, '中医中药'), (4, '健康服务管理')], default=0),
        ),
    ]
