# Generated by Django 4.2.11 on 2024-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_newsmodel_email_remove_newsmodel_landline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='Class',
            field=models.SmallIntegerField(choices=[(3, '西医西药'), (1, '医疗器械'), (4, '健康服务管理'), (2, '中医中药'), (0, '食品和农产品')], default=0),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Status',
            field=models.SmallIntegerField(choices=[(3, '西医西药'), (1, '医疗器械'), (4, '健康服务管理'), (2, '中医中药'), (0, '食品和农产品')], default=0),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='Time',
            field=models.DateField(),
        ),
    ]
