# Generated by Django 4.2.11 on 2024-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_companymodel_class_alter_companymodel_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Cumulative', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Class',
            field=models.SmallIntegerField(choices=[(7, '中医院与名中医'), (6, '天然药物原生药材'), (8, '医药新特品种'), (3, '大型仪器设备公司'), (4, '中小型医疗设备公司'), (5, '重要产业园及种植基地'), (12, '健康体检中心'), (13, '健康护理服务机构'), (9, '生物制药'), (0, '食品公司'), (11, '健康管理咨询机构'), (1, '农产品公司'), (10, '西医院与名西医'), (16, '医疗美容专用产品公司'), (15, '医疗美容门诊机构'), (2, '医药试剂公司'), (14, '化妆品公司')], default=0),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='Status',
            field=models.SmallIntegerField(choices=[(7, '中医院与名中医'), (6, '天然药物原生药材'), (8, '医药新特品种'), (3, '大型仪器设备公司'), (4, '中小型医疗设备公司'), (5, '重要产业园及种植基地'), (12, '健康体检中心'), (13, '健康护理服务机构'), (9, '生物制药'), (0, '食品公司'), (11, '健康管理咨询机构'), (1, '农产品公司'), (10, '西医院与名西医'), (16, '医疗美容专用产品公司'), (15, '医疗美容门诊机构'), (2, '医药试剂公司'), (14, '化妆品公司')], default=0),
        ),
    ]
